config:
    liveReloadPort: 35740
    files:
        img:
            src: web/img/**/*.{png,jpg,gif}
        js:
            vendor:
                src:
                    - web/vendor/modernizr/modernizr.js
                    - web/vendor/threejs/build/three.js
                dest: web/build/vendor.js
                destMin: web/build/vendor.min.js
            app:
                src:
                    - web/js/apps/app.js
                    - web/js/apps/**/*.js
                    - '!web/js/apps/**/*.test.js'
                dest: web/build/app.js
                destMin: web/build/app.min.js
            tests:
                unit:
                    src:
                        - web/js/apps/*/app/**/*.test.js
                e2e:
                    baseUrl: http://base-angular.local,
                    specs:
                        - web//jsapps/contacts_app/test/*.js

            livereload: web/js/livereload.js
        scss:
            loadPaths:
                - web/css
                - web/vendor
                - web/vendor/bootstrap-sass-official/vendor/assets/stylesheets/bootstrap
                - web/vendor/bourbon/dist
                - web/vendor/neat/app/assets/stylesheets
            app:
                src:
                    - web/css/application.scss
                dest: web/css/main.css
        scssImport:
            watch:
                - web/css/**/*.scss
                - '!web/css/*.css'
                - '!web/css/application.scss'
        templates:
            watch:
                - web/js/apps/*/app/**/*.html
